import pyautogui
import time
num = input('Введите число от 1 до 8: ')
pyautogui.hotkey('alt', 'tab')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 'n')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(0.5)
pyautogui.hotkey('ctrl', str(num))


