import pyautogui
import time
pyautogui.hotkey('win','r')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.write('Zubnoj v 8:00')
time.sleep(1)
pyautogui.hotkey('ctrl','a')
pyautogui.hotkey('ctrl','c')
time.sleep(1)
pyautogui.hotkey('alt','f4')
time.sleep(1)
pyautogui.moveTo(1000, 540)
pyautogui.click()
time.sleep(1)
pyautogui.hotkey('win','r')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.hotkey('ctrl','v')
time.sleep(1)
pyautogui.hotkey('alt','f4')
time.sleep(1)
pyautogui.moveTo(1000, 540)
pyautogui.click()